import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'ori-whipped',
    name: 'Traditional Whipped Shea Butter (Ori)',
    category: 'Ori (Shea Butter)',
    price: 1200,
    description: 'Our signature whipped ivory shea butter, sourced directly from women’s cooperatives in Northern Nigeria. Gently cold-pressed and infused with light botanical oils to lock in intense moisture and restore elasticity to the skin.',
    ingredients: ['100% Organic Raw Butyrospermum Parkii (Shea Butter)', 'Cold-Pressed Cocos Nucifera (Coconut) Oil', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'Tocopherol (Vitamin E)', 'Essential Oil Blend (Sandalwood & Vanilla)'],
    skinTypes: ['Dry', 'Sensitive', 'Mature', 'Normal'],
    image: '/images/shea_butter_jar_1784483461841.jpg',
    stockStatus: 'in_stock',
    featured: true,
    rating: 4.9,
    reviewsCount: 124,
    size: '250ml',
    usage: 'Warm a small amount between the palms of your hands and gently massage into damp skin after bathing. Focus on dry areas like elbows, knees, and heels.'
  },
  {
    id: 'ori-raw',
    name: 'Raw Premium Gold Shea Butter',
    category: 'Ori (Shea Butter)',
    price: 1200,
    description: 'Unrefined, pure golden shea butter in its most authentic form. Rich in natural vitamins A, E, and F, this deeply healing salve is perfect for soothing eczema, sunburns, scars, and stretch marks.',
    ingredients: ['100% Unrefined Butyrospermum Parkii (Gold Shea Butter)'],
    skinTypes: ['Dry', 'Sensitive', 'Eczema-Prone'],
    image: '/images/shea_butter_jar_1784483461841.jpg',
    stockStatus: 'in_stock',
    featured: false,
    rating: 4.8,
    reviewsCount: 89,
    size: '200g',
    usage: 'Apply directly to irritated, dry, or damaged skin as needed. Safe for infants and extremely sensitive skin.'
  },
  {
    id: 'black-soap-liquid',
    name: 'Gentle Liquid Black Soap Cleanser',
    category: 'Black Soap',
    price: 1200,
    description: 'A traditional African black soap modernly formulated into a gentle liquid facial and body cleanser. Saponified wild-harvested cocoa pods and plantain skins deeply clarify pores without stripping skin of its natural moisture.',
    ingredients: ['Saponified Cocoa Pod Ash', 'Saponified Palm Kernel Oil', 'Raw Honey', 'Organic Aloe Barbadensis Leaf Juice', 'Melaleuca Alternifolia (Tea Tree) Leaf Oil', 'Lavandula Angustifolia (Lavender) Oil'],
    skinTypes: ['Oily', 'Combination', 'Acne-Prone'],
    image: '/images/black_soap_bar_1784483476475.jpg',
    stockStatus: 'in_stock',
    featured: true,
    rating: 4.7,
    reviewsCount: 156,
    size: '200ml',
    usage: 'Dispense 1-2 pumps onto damp hands, lather, and gently massage onto wet face in circular motions. Rinse thoroughly with lukewarm water.'
  },
  {
    id: 'black-soap-bar',
    name: 'Artisanal Herbal Black Soap Bar',
    category: 'Black Soap',
    price: 1200,
    description: 'Traditional solid black soap handcrafted with wild herbs and raw honey. Formulated to combat dark spots, blemishes, and uneven skin tone while offering a deep, refreshing, natural clean.',
    ingredients: ['Saponified Cocoa Pod Ash', 'Saponified Shea Butter', 'Palm Kernel Oil', 'Wild-Harvested Osun (Camwood) Powder', 'Raw Wild Honey', 'Citrus Limon (Lemon) Juice'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    image: '/images/black_soap_bar_1784483476475.jpg',
    stockStatus: 'in_stock',
    featured: false,
    rating: 4.6,
    reviewsCount: 94,
    size: '150g',
    usage: 'Lather the bar between wet hands or on a washcloth. Gently wash your face and body. Avoid leaving raw soap directly on the face for more than a minute.'
  },
  {
    id: 'herbal-mask-clay',
    name: 'Qunite Clarifying Herbal Clay Mask',
    category: 'Herbal Face Masks',
    price: 1000,
    description: 'A potent powdered mask blending mineral-rich volcanic clay with traditional West African herbs. It draws out deep-seated impurities, refines skin texture, and instantly brightens the complexion.',
    ingredients: ['Bentonite Clay', 'Kaolin Clay', 'Moringa Oleifera Leaf Powder', 'Santalum Album (Sandalwood) Powder', 'Avena Sativa (Oat) Kernel Flour'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    image: '/images/herbal_face_mask_1784483490050.jpg',
    stockStatus: 'in_stock',
    featured: true,
    rating: 4.9,
    reviewsCount: 74,
    size: '100g',
    usage: 'Mix 1 tablespoon of powder with equal parts water, raw honey, or rosewater to form a paste. Apply to face, let dry for 10-15 minutes, then rinse off gently.'
  },
  {
    id: 'body-scrub-coconut',
    name: 'Cocoa & Coffee Revitalizing Body Scrub',
    category: 'Body Scrub',
    price: 2500,
    description: 'An exfoliating body polish combining roasted Robusta coffee grounds and organic Nigerian cocoa butter. Sloughs away dead skin cells, stimulates circulation, and leaves a luxurious protective moisture barrier.',
    ingredients: ['Organic Coffea Arabica (Coffee) Grounds', 'Sucrose (Raw Cane Sugar)', 'Theobroma Cacao (Cocoa) Seed Butter', 'Prunus Amygdalus Dulcis (Sweet Almond) Oil', 'Cocos Nucifera (Coconut) Shreds'],
    skinTypes: ['Dry', 'Normal', 'Rough Texture'],
    image: '/images/herbal_body_scrub_1784483533481.jpg',
    stockStatus: 'in_stock',
    featured: false,
    rating: 4.8,
    reviewsCount: 65,
    size: '300g',
    usage: 'In the shower, gently massage a generous scoop onto wet skin in circular motions, focusing on areas prone to dryness or cellulite. Rinse thoroughly.'
  },
  {
    id: 'bath-soak-herbal',
    name: 'Sacred Forest Herbal Bath Soak',
    category: 'Herbal Bath Soak',
    price: 1500,
    description: 'A therapeutic mixture of Epsom salts, pink Himalayan salt, and dried indigenous African botanicals. Designed to soothe aching muscles, de-stress the mind, and soften the skin in a warm bath.',
    ingredients: ['Magnesium Sulfate (Epsom Salt)', 'Sodium Chloride (Himalayan Pink Salt)', 'Dried Hibiscus Sabdariffa Flowers', 'Dried Moringa Leaves', 'Cymbopogon Citratus (Lemongrass) Oil', 'Eucalyptus Globulus Leaf Oil'],
    skinTypes: ['All Skin Types'],
    image: '/images/herbal_bath_soak_1784483500007.jpg',
    stockStatus: 'in_stock',
    featured: false,
    rating: 5.0,
    reviewsCount: 42,
    size: '400g',
    usage: 'Dissolve half a cup of soak into a warm, running bath. Immerse yourself and soak for at least 20 minutes to absorb mineral and herbal benefits.'
  },
  {
    id: 'facial-oil-marula',
    name: 'Nectar of Marula Facial Oil',
    category: 'Facial Oils',
    price: 2500,
    description: 'An ultra-light, luxurious oil cold-pressed from the kernels of the wild Marula fruit tree. Rich in antioxidants and Omega 6 & 9, it absorbs instantly to nourish, defend, and give your skin a natural glowing luster.',
    ingredients: ['100% Pure Sclerocarya Birrea (Marula) Kernel Oil'],
    skinTypes: ['Mature', 'Dry', 'Combination', 'Normal'],
    image: '/images/facial_oil_dropper_1784483522678.jpg',
    stockStatus: 'low_stock',
    featured: true,
    rating: 4.9,
    reviewsCount: 110,
    size: '30ml',
    usage: 'Apply 2-3 drops onto clean, slightly damp face and neck morning and night. Can be used alone or mixed into your daily moisturizer.'
  },
  {
    id: 'turmeric-soap-bright',
    name: 'Golden Turmeric & Camwood Glow Soap',
    category: 'Turmeric Soap',
    price: 1200,
    description: 'A soothing and brightening bar formulated with organic turmeric root powder and indigenous African Camwood. It targets hyperpigmentation, calms inflammatory breakouts, and restores a balanced complexion.',
    ingredients: ['Saponified Coconut Oil', 'Saponified Shea Butter', 'Curcuma Longa (Turmeric) Root Powder', 'Baphia Nitida (Camwood) Bark Powder', 'Zingiber Officinale (Ginger) Root Oil', 'Honey'],
    skinTypes: ['Acne-Prone', 'Combination', 'Oily', 'Normal'],
    image: '/images/turmeric_soap_bar_1784483511815.jpg',
    stockStatus: 'in_stock',
    featured: true,
    rating: 4.8,
    reviewsCount: 185,
    size: '150g',
    usage: 'Lather onto wet hands or sponge, apply to face and body, rinse after 30 seconds. Perfect for daily facial cleansing to even out dark spots.'
  }
];
